### PR TITLE
Controllers test

### PR DESCRIPTION
**Pull request by brahimdidi**
In this part I added test to my controllers using rspec and capybara.

##Requierments
dd RSpec as a gem to your project.
Create a Request spec file for all your controllers.
Make sure that for each action you check:
If response status was correct.
If a correct template was rendered.
If the response body includes correct placeholder text.

### CODE REVIEW

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @brahimdidi,** 

### **Good job so far!**
There are some issues that you still need to work on to go to the next project but you are almost there!

## **Highlights**

- Linters are green ✅.
- PR is very good ✅.
- Commit messages are consistent ✅.


## Required Changes ♻️
_Check the comments under the review._

- **Hello and nice job adding the tests but there some of them are failing due to empty so please fix them.**

Capture d’écran 2022-08-30 181637


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by brahimdidi** [comment]
the helpers are not needed @dasileker , only the requests are required for this,.

**Comment by brahimdidi** [comment]
I commented out all unused tests, thanks.

**Comment by dasileker** [comment]
Hello @brahimdidi if they are not needed please remove them and submit again

**Review by ShoiraTa — APPROVED** [review]
## **STATUS: APPROVED  🟢 ** 
------
### Hi @brahimdidi, 

**Great work on making the changes requested by a previous reviewer 👏🏻** 

Your project is complete! . There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

5SW

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
